### ISSUE TITLE
AdMob plugin not ready

### ISSUE THREAD

**Issue by camerin** [gomobile/sample-hello-admob#1]
I have downloaded the Git Repo, built using Intel XDK. Uploaded the app to Android. on launch i get AdMob plugin not ready.

**Comment by eashtianjr** [comment]
Don't forget to check that the "com.rjfun.cordova.plugin.admob" Cordova plug-in is included in your project under the "Projects" Tab in the Cordova Plugins > Third party plugins section. You are also required to build your application with the "Cordova for Android" Build Target.
